axis_linear: 1  # Left thumb stick vertical
scale_linear: 1.5
scale_linear_turbo: 5.0

axis_angular: 0  # Left thumb stick horizontal
scale_angular: -1.0
scale_angular_turbo: -2.0

enable_button: 4  # Left trigger button
enable_turbo_button: 5  # Right trigger button
